<a href="https://colab.research.google.com/github/Gouthamreddy2507/python-course-work/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print(np)

arr1 = np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>
1-dim
[1 2 3 4 5]



In [3]:
import numpy as np

# Array of zeros
zeros = np.zeros((3, 3))
print(zeros)
# Array of ones
ones = np.ones((2, 4))
print(ones)
# Identity matrix
identity = np.eye(4)
print(identity)

# Array of a specific value
full_array = np.full((2, 3), 7)
print(full_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]]


In [5]:
zeros = np.zeros((6,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
ones = np.ones((6,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
full = np.full((5,9),False)
print(full)

[[False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]
 [False False False False False False False False False]]


In [14]:
rand_float = np.random.rand(3,3)
print(rand_float)

[[0.71840683 0.42361525 0.10888794]
 [0.73467173 0.67667647 0.6260595 ]
 [0.37472127 0.69478344 0.54053171]]


In [9]:
range = np.arange(2,101,2)
print(range)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [10]:
lin_space = np.linspace(100,499,5)
print(lin_space)

[100.   199.75 299.5  399.25 499.  ]


In [13]:
rand_int = np.random.randint(1,10,(1,30))
print(rand_int)

[[7 4 4 7 2 6 6 1 7 5 5 2 3 2 1 3 1 1 5 2 8 1 3 3 6 1 9 3 7 6]]


In [16]:
rand_norm = np.random.randn(3,3)
print(rand_norm)

[[ 0.12907044  0.50744584 -0.58295902]
 [ 0.51981623 -0.50415282 -1.79361447]
 [ 0.05557463  0.89344588 -0.4141434 ]]


In [17]:
rand_choice = np.random.choice(['teja','kalyan','bhavani','pavani','vishwas'],2)
print(rand_choice)

['teja' 'bhavani']


In [35]:
np.random.seed(42)
rand_arr = np.random.randint(10)
print(rand_arr)

8


In [36]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [38]:
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [39]:
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [40]:
transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [41]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [45]:
matrix = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(matrix[1,2])
print(matrix[1:,0])
print(matrix[0:1,0:2])

60
[40 70]
[[10 20]]


In [46]:
arr = np.array([4,9,16,25,36])

In [48]:
print(arr + 1)
print(arr * 2)
print(arr ** 2)


[ 5 10 17 26 37]
[ 8 18 32 50 72]
[  16   81  256  625 1296]


In [49]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [50]:
print(np.std(arr))
print(np.var(arr))

11.436782764396638
130.8


In [51]:
print(np.min(arr))
print(np.max(arr))

4
36


In [52]:
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 4 13 29 54 90]
[     4     36    576  14400 518400]


In [53]:
print(arr <= 30)
print(arr[arr <= 30])

[ True  True  True  True False]
[ 4  9 16 25]


In [55]:
arr = np.array([3,4,2,4,1,5,8,4,3,6])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 3 4 4 4 5 6 8]
